name: 🚀 Deploy to HostGator cPanel

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3
      
    - name: 📂 Deploy via LFTP
      run: |
        sudo apt-get update
        sudo apt-get install -y lftp
        echo "Connecting to FTP server..."
        lftp -c "
          set ftp:ssl-allow no;
          set ftp:passive-mode yes;
          set net:timeout 30;
          set net:max-retries 2;
          open -u ${{ secrets.FTP_USERNAME }},${{ secrets.FTP_PASSWORD }} ftp.2a3avestibulares.com;
          pwd;
          ls -la;
          cd /;
          pwd;
          ls -la;
          quit
        "
